#!/bin/bash
set -e

SESSIONS_DIR="/var/www/html/.sessions"

# Create .sessions dir if it doesn't exists
if [ ! -d "$SESSIONS_DIR" ]; then
    mkdir "$SESSIONS_DIR"
    chown www-data:www-data "$SESSIONS_DIR"

    # www-data cannot delete the .sessions folder
    mkdir "$SESSIONS_DIR/.keep"
    chmod 700 "$SESSIONS_DIR/.keep"
    touch "$SESSIONS_DIR/.keep/.keep"
    chmod 600 "$SESSIONS_DIR/.keep/.keep"
fi

# Custom apache config
DOCUMENT_ROOT=`grep -oP 'DocumentRoot=\K(.+)' /var/www/html/.hosting_config || true`
if [ ! -z "$DOCUMENT_ROOT" ]; then
    echo "DocumentRoot \"/var/www/html/$DOCUMENT_ROOT\"" >> /etc/apache2/conf-available/custom-config.conf
fi
URL_PREFIX=`grep -oP 'UrlPrefix=\K(.+)' /var/www/html/.hosting_config || true`
if [ ! -z "$URL_PREFIX" ]; then
    if [ ! -z "$DOCUMENT_ROOT" ]; then
        echo "Alias \"$URL_PREFIX\" \"/var/www/html/$DOCUMENT_ROOT\"" >> /etc/apache2/conf-available/custom-config.conf
    else
        echo "Alias \"$URL_PREFIX\" \"/var/www/html\"" >> /etc/apache2/conf-available/custom-config.conf
    fi
fi

# Execute original script
apache2-foreground
